---
- hosts: localhost
  connection: local
  remote_user: root

#  become_method: sudo

  tasks:
#   - name: Update APT cache
#     apt:
#      update_cache: yes
#     ignore_errors: yes
#     become_user: root 
   - include_vars: ../defaults/main.yml

   - name: Install package python apt 
     apt:
      pkg: python-apt 
     register: curl_install


   - name: Install package curl
     apt:
      pkg: curl
     register: curl_install

   - name: Install package expect 
     apt:
      pkg: expect 
     register: expect_install


   - name: install spinnaker 
     script: expect_spinnaker.exp  {{DEV_USER}} 
     register: spinnaker_install

   - debug: var=spinnaker_install

   - name: Hal configuration version 
     shell: hal config version edit --version 1.5.4
     register: out_1 

   - name: Hal configuration storage 
     shell: hal config storage edit --type redis
     register: out_2

   - name: add halyard account
     script: expect_hal_account.exp {{DEV_USER}} {{REPO_NAME}} {{USER_NAME}} {{ REPO_PWD}} 
     register: spinnaker_install

   - name: add docker registery account
     shell: hal config provider docker-registry enable --no-validate
     register: out_1


   - name: add kubernetes account
     shell: hal config provider kubernetes account add my-kube-account --kubeconfig-file ~/.kube/config --docker-registries my-docker-account-1 --debug 
     register: out_1

   - name: add kubernete account
     shell: hal config provider kubernetes enable --no-validate
     register: out_1



   - debug: var=spinnaker_install

#   - name: Hal configuration version
#     expect:
#      command: "hal config provider docker-registry account add my-docker-account-2 --address https://index.docker.io/ --repositories jabajaj/kubectl --username jabajaj --password"
#      responses:
#       Your docker registry password: "cisco123\n"

   - name: Hal deploy apply 
     shell: sudo hal deploy apply 
#     become_method: sudo 
     register: out_2
       

